@echo off
echo Fixing Next.js development server...
echo.
echo Step 1: Stopping any running Node processes...
taskkill /f /im node.exe 2>nul
echo.
echo Step 2: Clearing Next.js cache...
rmdir /s /q .next 2>nul
echo.
echo Step 3: Rebuilding project...
npm run build
echo.
echo Step 4: Starting fresh development server...
npm run dev