import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('en');

  // Load saved language from localStorage
  useEffect(() => {
    const savedLanguage = localStorage.getItem('bridgeLanguage');
    if (savedLanguage && ['en', 'hi', 'or'].includes(savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when changed
  const changeLanguage = (language) => {
    console.log('Language changed to:', language);
    setCurrentLanguage(language);
    localStorage.setItem('bridgeLanguage', language);
  };

  const value = {
    currentLanguage,
    changeLanguage,
    t: (key) => {
      const translation = translations[currentLanguage]?.[key] || translations.en?.[key] || key;
      // console.log(`Translation for "${key}" in "${currentLanguage}":`, translation);
      return translation;
    }
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// Translation data
const translations = {
  en: {
    // Header
    'header.logo': 'BriDGe',
    'header.search': 'Search opportunities, courses, mentors...',
    'header.opportunities': 'Opportunities',
    'header.mentors': 'Mentors',
    'header.games': 'Games',
    'header.badges': 'Badges',
    'header.aipro': 'AI Pro',
    'header.profile': 'Profile',
    
    // Home Page
    'home.hero.title': 'Bridge the Gap, Build the Future',
    'home.hero.subtitle': 'Connect with opportunities, mentors, and resources to accelerate your career journey',
    'home.hero.getStarted': 'Get Started',
    'home.hero.learnMore': 'Learn More',
    'home.stats.opportunities': 'Opportunities',
    'home.stats.mentors': 'Mentors',
    'home.stats.students': 'Students',
    
    // Profile
    'profile.title': 'Profile',
    'profile.viewProfile': 'View Profile →',
    'profile.personalInfo': 'Personal Information',
    'profile.education': 'Education',
    'profile.skills': 'Skills & Languages',
    'profile.experience': 'Experience & Projects',
    'profile.additional': 'Additional Info',
    'profile.save': 'Save Changes',
    'profile.preview': 'Preview Profile',
    'profile.profileViews': 'Profile Views',
    'profile.achievements': 'Achievements',
    'profile.currentLevel': 'Current Level',
    'profile.skillsExpertise': 'Skills & Expertise',
    'profile.achievementsBadges': 'Achievements & Badges',
    'profile.recentActivity': 'Recent Activity',
    'profile.viewAllBadges': 'View All Badges',
    'profile.email': 'Email',
    'profile.location': 'Location',
    'profile.university': 'University',
    'profile.graduationYear': 'Graduation Year',
    'profile.earned': 'Earned',
    'profile.inProgress': 'In Progress',
    'profile.completedCourse': 'Completed React Course',
    'profile.earnedBadge': 'Earned Code Master Badge',
    'profile.joinedTeam': 'Joined Hackathon Team',
    'profile.updatedProfile': 'Updated Profile',
    'profile.hoursAgo': 'hours ago',
    'profile.dayAgo': 'day ago',
    'profile.daysAgo': 'days ago',
    'profile.weekAgo': 'week ago',
    
    // Profile Edit
    'profileEdit.personalInfo.title': 'Personal Information',
    'profileEdit.firstName': 'First Name',
    'profileEdit.lastName': 'Last Name',
    'profileEdit.email': 'Email Address',
    'profileEdit.phone': 'Phone Number',
    'profileEdit.dateOfBirth': 'Date of Birth',
    'profileEdit.gender': 'Gender',
    'profileEdit.nationality': 'Nationality',
    'profileEdit.location': 'Current Location',
    'profileEdit.address': 'Full Address',
    'profileEdit.bio': 'Bio / About Yourself',
    'profileEdit.socialLinks': 'Social Links',
    'profileEdit.linkedin': 'LinkedIn Profile',
    'profileEdit.github': 'GitHub Profile',
    'profileEdit.portfolio': 'Portfolio Website',
    
    // Education
    'education.title': 'Education Details',
    'education.current': 'Current Education',
    'education.previous': 'Previous Education',
    'education.institution': 'Institution Name',
    'education.degree': 'Degree',
    'education.field': 'Field of Study',
    'education.semester': 'Current Semester',
    'education.cgpa': 'Current CGPA / Percentage',
    'education.startYear': 'Start Year',
    'education.endYear': 'Expected End Year',
    'education.addEducation': '+ Add Education',
    'education.removeEducation': 'Remove Education',
    
    // Skills
    'skills.title': 'Skills & Languages',
    'skills.technical': 'Technical Skills',
    'skills.soft': 'Soft Skills',
    'skills.languages': 'Languages Known',
    'skills.addTechnical': 'Add a technical skill and press Enter',
    'skills.addSoft': 'Add a soft skill and press Enter',
    'skills.addLanguage': 'Add a language and press Enter',
    
    // Experience
    'experience.title': 'Experience & Projects',
    'experience.work': 'Work Experience',
    'experience.projects': 'Projects',
    'experience.company': 'Company',
    'experience.position': 'Position',
    'experience.startDate': 'Start Date',
    'experience.endDate': 'End Date',
    'experience.description': 'Description',
    'experience.addExperience': '+ Add Experience',
    'experience.addProject': '+ Add Project',
    'experience.projectName': 'Project Name',
    'experience.projectLink': 'Project Link',
    'experience.remove': 'Remove',
    
    // Additional Info
    'additional.title': 'Additional Information',
    'additional.achievements': 'Achievements & Awards',
    'additional.extracurricular': 'Extracurricular Activities',
    'additional.careerGoals': 'Career Goals & Interests',
    'additional.jobRoles': 'Preferred Job Roles',
    'additional.salary': 'Expected Salary Range',
    
    // Common
    'common.backToProfile': '← Back to Profile',
    'common.male': 'Male',
    'common.female': 'Female',
    'common.other': 'Other',
    'common.preferNotToSay': 'Prefer not to say',
    'common.required': '*',
    
    // Featured Updates
    'featured.title': 'Featured Updates',
    'featured.subtitle': 'Stay updated with the latest opportunities and news',
    'featured.aiTool.title': 'New AI-Powered Career Guidance Tool Launched',
    'featured.aiTool.description': 'Get personalized career recommendations with our latest AI technology',
    'featured.gsoc.title': 'Google Summer of Code 2024 Applications Open',
    'featured.gsoc.description': 'Apply now for exciting open source projects with top tech companies',
    'featured.partnership.title': 'New Partnership with Top Universities',
    'featured.partnership.description': 'Access exclusive courses and mentorship from leading institutions',
    'featured.productUpdate': 'Product Update',
    'featured.opportunity': 'Opportunity',
    'featured.partnershipCategory': 'Partnership',
    
    // Jobs Section
    'jobs.title': 'Job Opportunities',
    'jobs.availableJobs': 'Available Jobs',
    'jobs.recommendedJobs': 'Recommended Jobs',
    'jobs.match': 'Match',
    'jobs.applyNow': 'Apply Now',
    'jobs.fullTime': 'Full-time',
    'jobs.partTime': 'Part-time',
    'jobs.remote': 'Remote',
    
    // Courses Section
    'courses.title': 'Learning Courses',
    'courses.youtube': 'YouTube Courses',
    'courses.coursera': 'Coursera Courses',
    'courses.enrollNow': 'Enroll Now',
    'courses.certificate': 'Certificate',
    'courses.students': 'students',
    'courses.hours': 'hours',
    'courses.months': 'months',
    
    // Opportunities Page
    'opportunities.title': 'Discover Opportunities',
    'opportunities.subtitle': 'Explore thousands of jobs, internships, hackathons, and competitions to accelerate your career',
    'opportunities.allOpportunities': 'All Opportunities',
    'opportunities.jobs': 'Jobs',
    'opportunities.internships': 'Internships',
    'opportunities.hackathons': 'Hackathons',
    'opportunities.competitions': 'Competitions',
    'opportunities.found': 'Opportunities Found',
    'opportunities.totalApplicants': 'Total Applicants',
    'opportunities.deadline': 'Deadline',
    'opportunities.requiredSkills': 'Required Skills',
    'opportunities.applied': 'applied',
    'opportunities.applyNow': 'Apply Now',
    'opportunities.job': 'Job',
    'opportunities.internship': 'Internship',
    'opportunities.hackathon': 'Hackathon',
    'opportunities.competition': 'Competition',
    
    // Mentors Page
    'mentors.title': 'Connect with Mentors',
    'mentors.subtitle': 'Learn directly from industry leaders, alumni, and professionals shaping the future.',
    'mentors.intro': 'Whether you\'re exploring career paths, preparing for interviews, or building real-world projects — connect with mentors who\'ve been there. Gain personalized guidance, career insights, and networking opportunities that help you bridge the gap between learning and success.',
    'mentors.searchPlaceholder': 'Search mentors by skill, company, or domain...',
    'mentors.allMentors': 'All Mentors',
    'mentors.techDevelopment': 'Tech & Development',
    'mentors.dataScience': 'Data Science & AI',
    'mentors.careerSkills': 'Career & Soft Skills',
    'mentors.designCreativity': 'Design & Creativity',
    'mentors.entrepreneurship': 'Entrepreneurship',
    'mentors.alumni': 'Alumni Mentors',
    'mentors.available': 'Mentors Available',
    'mentors.totalSessions': 'Total Sessions',
    'mentors.aiRecommendation': 'AI Mentor Recommendation',
    'mentors.basedOnInterests': 'Based on your interests in Machine Learning:',
    'mentors.connect': 'Connect',
    'mentors.upcomingEvents': 'Upcoming Mentor Events',
    'mentors.joinLiveSessions': 'Join live mentor sessions every weekend.',
    'mentors.join': 'Join',
    'mentors.viewAllEvents': 'View All Events →',
    'mentors.expertise': 'Expertise',
    'mentors.availability': 'Availability',
    'mentors.sessions': 'Sessions',
    'mentors.completed': 'completed',
    'mentors.experience': 'Experience',
    'mentors.bookSession': 'Book Session',
    'mentors.viewProfile': 'View Profile',
    'mentors.message': 'Message',
    'mentors.quote1': 'Great mentorship turns potential into performance.',
    'mentors.quote2': 'Every bridge starts with a mentor who guides the first step.',
    
    // Games Page
    'games.title': 'Level Up Your Skills',
    'games.subtitle': 'Master your career through interactive games, challenges, and simulations',
    'games.gamesPlayed': 'Games Played',
    'games.skillPoints': 'Skill Points',
    'games.badges': 'Badges',
    'games.level': 'Level',
    'games.playNow': 'Play Now',
    'games.learnMore': 'Learn More',
    'games.achievements': 'Your Achievements',
    'games.leaderboard': 'Global Leaderboard',
    'games.features': 'Features',
    'games.rewards': 'Rewards',
    'games.estimatedTime': 'Estimated Time',
    'games.difficulty': 'Difficulty',
    'games.players': 'Players',
    'games.rating': 'Rating',
    'games.backToGames': '← Back to Games',
    
    // Badges Page
    'badges.title': 'Badge Collection',
    'badges.subtitle': 'Showcase your achievements and unlock exclusive rewards',
    'badges.allBadges': 'All Badges',
    'badges.earned': 'Earned',
    'badges.locked': 'Locked',
    'badges.bridgePro': 'BriDGe Pro',
    'badges.totalBadges': 'Total Badges',
    'badges.rareBadges': 'Rare Badges',
    'badges.epicBadges': 'Epic Badges',
    'badges.legendaryBadges': 'Legendary Badges',
    'badges.bridgeProBadges': 'BriDGe Pro Badges',
    'badges.earnedOn': 'Earned on',
    'badges.progress': 'Progress',
    'badges.xpReward': 'XP Reward',
    'badges.unlockWithPro': 'Unlock with BriDGe Pro',
    'badges.getProAccess': 'Get Pro Access',
    'badges.backToBadges': '← Back to Badges',
    
    // Profile Sidebar
    'sidebar.profile': 'Profile',
    'sidebar.viewProfile': 'View Profile →',
    'sidebar.computerScienceStudent': '🎓 Computer Science Student',
    'sidebar.quickActions': 'Quick Actions',
    'sidebar.editProfile': 'Edit Profile',
    'sidebar.settings': 'Settings',
    'sidebar.help': 'Help & Support',
    'sidebar.recentActivity': 'Recent Activity',
    'sidebar.completedCourse': 'Completed React Course',
    'sidebar.earnedBadge': 'Earned Code Master Badge',
    'sidebar.joinedTeam': 'Joined Hackathon Team',
    'sidebar.proFeatures': 'Pro Features',
    'sidebar.aiMentor': 'AI Mentor Chat',
    'sidebar.premiumCourses': 'Premium Courses',
    'sidebar.prioritySupport': 'Priority Support',
    'sidebar.upgradeToPro': 'Upgrade to Pro',
    'sidebar.profileCompletion': 'Profile Completion',
    'sidebar.completeProfile': 'Complete your profile to unlock more opportunities!',
    'sidebar.completeMyProfile': 'Complete my profile →',
    'sidebar.navigation': 'Navigation',
    'sidebar.quickActions': 'Quick Actions',
    'sidebar.findJobs': 'Find Jobs',
    'sidebar.findMentors': 'Find Mentors',
    'sidebar.practice': 'Practice',
    'sidebar.badges': 'Badges',
    'sidebar.recentActivity': 'Recent Activity',
    'sidebar.appliedToGoogle': 'Applied to Google Internship',
    'sidebar.earnedCodeMaster': 'Earned Code Master badge',
    'sidebar.completedReact': 'Completed React Course',
    'sidebar.hoursAgo': 'hours ago',
    'sidebar.dayAgo': 'day ago',
    'sidebar.daysAgo': 'days ago',
    'sidebar.bridgeProFeatures': 'Bridge Pro Features',
    'sidebar.aiCareerGuidance': 'AI Career Guidance',
    'sidebar.getPersonalizedAdvice': 'Get personalized career advice',
    'sidebar.priorityApplications': 'Priority Applications',
    'sidebar.skipQueue': 'Skip the queue with priority',
    'sidebar.advancedAnalytics': 'Advanced Analytics',
    'sidebar.detailedInsights': 'Detailed performance insights',
    'sidebar.settings': 'Settings',
    'sidebar.logout': 'Logout',
    'sidebar.gamesAndPractice': 'Games & Practice',
    'sidebar.badgesAndAchievements': 'Badges & Achievements',
    
    // AI Pro Page
    'aipro.title': 'BriDGe AI Pro',
    'aipro.subtitle': 'Supercharge your career with advanced AI-powered tools and insights',
    'aipro.aiRecommendations': 'AI Recommendations',
    'aipro.successRate': 'Success Rate',
    'aipro.aiAssistant': 'AI Assistant',
    'aipro.aiPoweredFeatures': '🚀 AI-Powered Features',
    'aipro.chooseYourPlan': '💎 Choose Your AI Pro Plan',
    'aipro.successStories': '🌟 Success Stories',
    'aipro.mostPopular': 'Most Popular',
    'aipro.startFreeTrial': 'Start Free Trial',
    'aipro.getStarted': 'Get Started',
    'aipro.careerGuidance': 'AI Career Guidance',
    'aipro.careerGuidanceDesc': 'Get personalized career recommendations powered by advanced machine learning',
    'aipro.smartMatching': 'Smart Job Matching',
    'aipro.smartMatchingDesc': 'AI-powered job recommendations with 95% accuracy based on your profile',
    'aipro.skillAnalysis': 'Skill Gap Analysis',
    'aipro.skillAnalysisDesc': 'Advanced AI analysis of your skills vs market demands',
    'aipro.interviewCoach': 'AI Interview Coach',
    'aipro.interviewCoachDesc': 'Practice with AI interviewer and get real-time feedback',
    'aipro.resumeOptimizer': 'Resume AI Optimizer',
    'aipro.resumeOptimizerDesc': 'AI-powered resume analysis with ATS optimization',
    'aipro.marketInsights': 'AI Market Insights',
    'aipro.marketInsightsDesc': 'Real-time market analysis and salary predictions',
    'aipro.mentorMatching': 'AI Mentor Matching',
    'aipro.mentorMatchingDesc': 'Find perfect mentors using AI compatibility analysis',
    'aipro.personalizedLearning': 'Personalized Learning',
    'aipro.personalizedLearningDesc': 'AI-curated learning paths based on your career goals',
    'aipro.salaryNegotiator': 'AI Salary Negotiator',
    'aipro.salaryNegotiatorDesc': 'AI-powered salary negotiation strategies and market data',
    'aipro.networkBuilder': 'AI Network Builder',
    'aipro.networkBuilderDesc': 'Smart networking recommendations and connection strategies',
    'aipro.careerPredictor': 'Career Path Predictor',
    'aipro.careerPredictorDesc': 'AI predictions for your career trajectory and opportunities',
    'aipro.portfolioBuilder': 'AI Portfolio Builder',
    'aipro.portfolioBuilderDesc': 'Create stunning portfolios with AI-generated content and design',
    
    // Common Sections
    'common.internships': 'Internships',
    'common.networking': 'Networking',
    'common.mockPractice': 'Mock Practice',
    'common.applyNow': 'Apply Now',
    'common.learnMore': 'Learn More',
    'common.viewAll': 'View All',
    
    // Networking Section
    'networking.title': 'Connect & Network',
    'networking.mentors': 'Mentors',
    'networking.alumni': 'Alumni',
    'networking.peers': 'Peers',
    'networking.connectNow': 'Connect Now',
    'networking.bookSession': 'Book Session',
    'networking.sendMessage': 'Send Message',
    'networking.years': 'years',
    'networking.sessions': 'sessions',
    
    // Mock Practice Section
    'mockPractice.title': 'Mock Practice & Interviews',
    'mockPractice.technicalInterview': 'Technical Interview',
    'mockPractice.behavioralInterview': 'Behavioral Interview',
    'mockPractice.caseStudy': 'Case Study',
    'mockPractice.startPractice': 'Start Practice',
    'mockPractice.difficulty': 'Difficulty',
    'mockPractice.duration': 'Duration',
    'mockPractice.earnBadges': 'Earn Badges',
    'mockPractice.unlockAchievements': 'Unlock achievements as you complete challenges',
    
    // Games Content
    'games.logicLoop': 'LogicLoop',
    'games.careerXP': 'CareerXP',
    'games.logicCoding': 'Logic & Coding',
    'games.careerSimulation': 'Career Simulation',
    'games.intermediate': 'Intermediate',
    'games.beginner': 'Beginner',
    'games.advanced': 'Advanced',
    'games.minPerSession': 'min per session',
    'games.minPerChallenge': 'min per challenge',
    'games.masterCoding': 'Master coding logic through interactive MCQ challenges that test your problem-solving skills.',
    'games.progressAlgorithmic': 'Progress through algorithmic puzzles, data structure questions, and programming concepts.',
    'games.competeRealTime': 'Compete with peers in real-time logic battles and climb the global leaderboard.',
    'games.unlockAdvanced': 'Unlock advanced topics like dynamic programming, graph theory, and system design.',
    'games.createAvatar': 'Create your professional avatar and embark on realistic career challenges.',
    'games.buildResumes': 'Build resumes, solve industry puzzles, and practice mini-interviews in immersive scenarios.',
    'games.progressJobRoles': 'Progress through different job roles and unlock career storylines based on real companies.',
    'games.earnBadgesPoints': 'Earn badges, skill points, and mentorship opportunities as you advance through levels.',
    'games.moreInfo': 'More Info',
    'games.badgesEarned': 'Badges Earned',
    'games.inProgress': 'In Progress',
    'games.completionRate': 'Completion Rate',
    'games.earnedBadges': 'Earned Badges',
    
    // Badge Names and Descriptions
    'badges.codeMaster': 'Code Master',
    'badges.codeMasterDesc': 'Complete 50 coding challenges',
    'badges.aiExplorer': 'AI Explorer',
    'badges.aiExplorerDesc': 'Complete AI learning path',
    'badges.quickLearner': 'Quick Learner',
    'badges.quickLearnerDesc': 'Complete courses in record time',
    'badges.profilePro': 'Profile Pro',
    'badges.profileProDesc': 'Complete your profile 100%',
    'badges.legendary': 'LEGENDARY',
    'badges.epic': 'EPIC',
    'badges.rare': 'RARE',
    'badges.common': 'COMMON',
    
    // Mentor Events
    'mentorEvents.resumeReview': 'Resume Review with Priya',
    'mentorEvents.systemDesign': 'System Design Masterclass with Aakash',
    'mentorEvents.aiCareerGuidance': 'AI Career Guidance Session',
    'mentorEvents.joinButton': 'शामिल हों',
    'mentorEvents.viewAllEvents': 'सभी इवेंट्स देखें',
    
    // Language Selector
    'language.english': 'English',
    'language.hindi': 'हिंदी',
    'language.odia': 'ଓଡ଼ିଆ'
  },
  
  hi: {
    // Header
    'header.logo': 'BriDGe',
    'header.search': 'अवसर, कोर्स, मेंटर खोजें...',
    'header.opportunities': 'अवसर',
    'header.mentors': 'मेंटर',
    'header.games': 'गेम्स',
    'header.badges': 'बैज',
    'header.aipro': 'AI प्रो',
    'header.profile': 'प्रोफाइल',
    
    // Home Page
    'home.hero.title': 'अंतर को पाटें, भविष्य बनाएं',
    'home.hero.subtitle': 'अपनी करियर यात्रा को तेज़ करने के लिए अवसरों, मेंटर्स और संसाधनों से जुड़ें',
    'home.hero.getStarted': 'शुरू करें',
    'home.hero.learnMore': 'और जानें',
    'home.stats.opportunities': 'अवसर',
    'home.stats.mentors': 'मेंटर',
    'home.stats.students': 'छात्र',
    
    // Profile
    'profile.title': 'प्रोफाइल',
    'profile.viewProfile': 'प्रोफाइल देखें →',
    'profile.personalInfo': 'व्यक्तिगत जानकारी',
    'profile.education': 'शिक्षा',
    'profile.skills': 'कौशल और भाषाएं',
    'profile.experience': 'अनुभव और प्रोजेक्ट',
    'profile.additional': 'अतिरिक्त जानकारी',
    'profile.save': 'परिवर्तन सहेजें',
    'profile.preview': 'प्रोफाइल पूर्वावलोकन',
    'profile.profileViews': 'प्रोफाइल दृश्य',
    'profile.achievements': 'उपलब्धियां',
    'profile.currentLevel': 'वर्तमान स्तर',
    'profile.skillsExpertise': 'कौशल और विशेषज्ञता',
    'profile.achievementsBadges': 'उपलब्धियां और बैज',
    'profile.recentActivity': 'हाल की गतिविधि',
    'profile.viewAllBadges': 'सभी बैज देखें',
    'profile.email': 'ईमेल',
    'profile.location': 'स्थान',
    'profile.university': 'विश्वविद्यालय',
    'profile.graduationYear': 'स्नातक वर्ष',
    'profile.earned': 'अर्जित',
    'profile.inProgress': 'प्रगति में',
    'profile.completedCourse': 'रिएक्ट कोर्स पूरा किया',
    'profile.earnedBadge': 'कोड मास्टर बैज अर्जित किया',
    'profile.joinedTeam': 'हैकाथॉन टीम में शामिल हुए',
    'profile.updatedProfile': 'प्रोफाइल अपडेट किया',
    'profile.hoursAgo': 'घंटे पहले',
    'profile.dayAgo': 'दिन पहले',
    'profile.daysAgo': 'दिन पहले',
    'profile.weekAgo': 'सप्ताह पहले',
    
    // Profile Edit
    'profileEdit.personalInfo.title': 'व्यक्तिगत जानकारी',
    'profileEdit.firstName': 'पहला नाम',
    'profileEdit.lastName': 'अंतिम नाम',
    'profileEdit.email': 'ईमेल पता',
    'profileEdit.phone': 'फोन नंबर',
    'profileEdit.dateOfBirth': 'जन्म तिथि',
    'profileEdit.gender': 'लिंग',
    'profileEdit.nationality': 'राष्ट्रीयता',
    'profileEdit.location': 'वर्तमान स्थान',
    'profileEdit.address': 'पूरा पता',
    'profileEdit.bio': 'बायो / अपने बारे में',
    'profileEdit.socialLinks': 'सोशल लिंक',
    'profileEdit.linkedin': 'लिंक्डइन प्रोफाइल',
    'profileEdit.github': 'गिटहब प्रोफाइल',
    'profileEdit.portfolio': 'पोर्टफोलियो वेबसाइट',
    
    // Education
    'education.title': 'शिक्षा विवरण',
    'education.current': 'वर्तमान शिक्षा',
    'education.previous': 'पिछली शिक्षा',
    'education.institution': 'संस्थान का नाम',
    'education.degree': 'डिग्री',
    'education.field': 'अध्ययन क्षेत्र',
    'education.semester': 'वर्तमान सेमेस्टर',
    'education.cgpa': 'वर्तमान CGPA / प्रतिशत',
    'education.startYear': 'प्रारंभ वर्ष',
    'education.endYear': 'अपेक्षित समाप्ति वर्ष',
    'education.addEducation': '+ शिक्षा जोड़ें',
    'education.removeEducation': 'शिक्षा हटाएं',
    
    // Skills
    'skills.title': 'कौशल और भाषाएं',
    'skills.technical': 'तकनीकी कौशल',
    'skills.soft': 'सॉफ्ट स्किल्स',
    'skills.languages': 'ज्ञात भाषाएं',
    'skills.addTechnical': 'तकनीकी कौशल जोड़ें और एंटर दबाएं',
    'skills.addSoft': 'सॉफ्ट स्किल जोड़ें और एंटर दबाएं',
    'skills.addLanguage': 'भाषा जोड़ें और एंटर दबाएं',
    
    // Experience
    'experience.title': 'अनुभव और प्रोजेक्ट',
    'experience.work': 'कार्य अनुभव',
    'experience.projects': 'प्रोजेक्ट्स',
    'experience.company': 'कंपनी',
    'experience.position': 'पद',
    'experience.startDate': 'प्रारंभ तिथि',
    'experience.endDate': 'समाप्ति तिथि',
    'experience.description': 'विवरण',
    'experience.addExperience': '+ अनुभव जोड़ें',
    'experience.addProject': '+ प्रोजेक्ट जोड़ें',
    'experience.projectName': 'प्रोजेक्ट का नाम',
    'experience.projectLink': 'प्रोजेक्ट लिंक',
    'experience.remove': 'हटाएं',
    
    // Additional Info
    'additional.title': 'अतिरिक्त जानकारी',
    'additional.achievements': 'उपलब्धियां और पुरस्कार',
    'additional.extracurricular': 'पाठ्येतर गतिविधियां',
    'additional.careerGoals': 'करियर लक्ष्य और रुचियां',
    'additional.jobRoles': 'पसंदीदा नौकरी भूमिकाएं',
    'additional.salary': 'अपेक्षित वेतन सीमा',
    
    // Common
    'common.backToProfile': '← प्रोफाइल पर वापस',
    'common.male': 'पुरुष',
    'common.female': 'महिला',
    'common.other': 'अन्य',
    'common.preferNotToSay': 'नहीं बताना चाहते',
    'common.required': '*',
    
    // Featured Updates
    'featured.title': 'विशेष अपडेट',
    'featured.subtitle': 'नवीनतम अवसरों और समाचारों के साथ अपडेट रहें',
    'featured.aiTool.title': 'नया AI-संचालित करियर मार्गदर्शन उपकरण लॉन्च',
    'featured.aiTool.description': 'हमारी नवीनतम AI तकनीक के साथ व्यक्तिगत करियर सिफारिशें प्राप्त करें',
    'featured.gsoc.title': 'Google Summer of Code 2024 आवेदन खुले',
    'featured.gsoc.description': 'शीर्ष तकनीकी कंपनियों के साथ रोमांचक ओपन सोर्स प्रोजेक्ट्स के लिए अभी आवेदन करें',
    'featured.partnership.title': 'शीर्ष विश्वविद्यालयों के साथ नई साझेदारी',
    'featured.partnership.description': 'अग्रणी संस्थानों से विशेष पाठ्यक्रम और मेंटरशिप तक पहुंच',
    'featured.productUpdate': 'उत्पाद अपडेट',
    'featured.opportunity': 'अवसर',
    'featured.partnershipCategory': 'साझेदारी',
    
    // Jobs Section
    'jobs.title': 'नौकरी के अवसर',
    'jobs.availableJobs': 'उपलब्ध नौकरियां',
    'jobs.recommendedJobs': 'सुझाई गई नौकरियां',
    'jobs.match': 'मैच',
    'jobs.applyNow': 'अभी आवेदन करें',
    'jobs.fullTime': 'पूर्णकालिक',
    'jobs.partTime': 'अंशकालिक',
    'jobs.remote': 'रिमोट',
    
    // Courses Section
    'courses.title': 'शिक्षण पाठ्यक्रम',
    'courses.youtube': 'YouTube पाठ्यक्रम',
    'courses.coursera': 'Coursera पाठ्यक्रम',
    'courses.enrollNow': 'अभी नामांकन करें',
    'courses.certificate': 'प्रमाणपत्र',
    'courses.students': 'छात्र',
    'courses.hours': 'घंटे',
    'courses.months': 'महीने',
    
    // Opportunities Page
    'opportunities.title': 'अवसर खोजें',
    'opportunities.subtitle': 'अपने करियर को तेज़ करने के लिए हजारों नौकरियों, इंटर्नशिप, हैकाथॉन और प्रतियोगिताओं का अन्वेषण करें',
    'opportunities.allOpportunities': 'सभी अवसर',
    'opportunities.jobs': 'नौकरियां',
    'opportunities.internships': 'इंटर्नशिप',
    'opportunities.hackathons': 'हैकाथॉन',
    'opportunities.competitions': 'प्रतियोगिताएं',
    'opportunities.found': 'अवसर मिले',
    'opportunities.totalApplicants': 'कुल आवेदक',
    'opportunities.deadline': 'अंतिम तिथि',
    'opportunities.requiredSkills': 'आवश्यक कौशल',
    'opportunities.applied': 'आवेदन किया',
    'opportunities.applyNow': 'अभी आवेदन करें',
    'opportunities.job': 'नौकरी',
    'opportunities.internship': 'इंटर्नशिप',
    'opportunities.hackathon': 'हैकाथॉन',
    'opportunities.competition': 'प्रतियोगिता',
    
    // Mentors Page
    'mentors.title': 'मेंटर्स से जुड़ें',
    'mentors.subtitle': 'उद्योग के नेताओं, पूर्व छात्रों और भविष्य को आकार देने वाले पेशेवरों से सीधे सीखें।',
    'mentors.intro': 'चाहे आप करियर पथ की खोज कर रहे हों, इंटरव्यू की तैयारी कर रहे हों, या वास्तविक दुनिया की परियोजनाएं बना रहे हों — उन मेंटर्स से जुड़ें जो वहां रहे हैं। व्यक्तिगत मार्गदर्शन, करियर अंतर्दृष्टि और नेटवर्किंग के अवसर प्राप्त करें।',
    'mentors.searchPlaceholder': 'कौशल, कंपनी या डोमेन द्वारा मेंटर्स खोजें...',
    'mentors.allMentors': 'सभी मेंटर्स',
    'mentors.techDevelopment': 'तकनीक और विकास',
    'mentors.dataScience': 'डेटा साइंस और AI',
    'mentors.careerSkills': 'करियर और सॉफ्ट स्किल्स',
    'mentors.designCreativity': 'डिज़ाइन और रचनात्मकता',
    'mentors.entrepreneurship': 'उद्यमिता',
    'mentors.alumni': 'पूर्व छात्र मेंटर्स',
    'mentors.available': 'उपलब्ध मेंटर्स',
    'mentors.totalSessions': 'कुल सत्र',
    'mentors.aiRecommendation': 'AI मेंटर सिफारिश',
    'mentors.basedOnInterests': 'मशीन लर्निंग में आपकी रुचि के आधार पर:',
    'mentors.connect': 'जुड़ें',
    'mentors.upcomingEvents': 'आगामी मेंटर इवेंट्स',
    'mentors.joinLiveSessions': 'हर सप्ताहांत लाइव मेंटर सत्र में शामिल हों।',
    'mentors.join': 'शामिल हों',
    'mentors.viewAllEvents': 'सभी इवेंट्स देखें →',
    'mentors.expertise': 'विशेषज्ञता',
    'mentors.availability': 'उपलब्धता',
    'mentors.sessions': 'सत्र',
    'mentors.completed': 'पूर्ण',
    'mentors.experience': 'अनुभव',
    'mentors.bookSession': 'सत्र बुक करें',
    'mentors.viewProfile': 'प्रोफाइल देखें',
    'mentors.message': 'संदेश',
    'mentors.quote1': 'महान मेंटरशिप क्षमता को प्रदर्शन में बदल देती है।',
    'mentors.quote2': 'हर पुल एक मेंटर से शुरू होता है जो पहला कदम दिखाता है।',
    
    // Games Page
    'games.title': 'अपने कौशल को बढ़ाएं',
    'games.subtitle': 'इंटरैक्टिव गेम्स, चुनौतियों और सिमुलेशन के माध्यम से अपने करियर में महारत हासिल करें',
    'games.gamesPlayed': 'खेले गए गेम्स',
    'games.skillPoints': 'स्किल पॉइंट्स',
    'games.badges': 'बैज',
    'games.level': 'स्तर',
    'games.playNow': 'अभी खेलें',
    'games.learnMore': 'और जानें',
    'games.achievements': 'आपकी उपलब्धियां',
    'games.leaderboard': 'ग्लोबल लीडरबोर्ड',
    'games.features': 'विशेषताएं',
    'games.rewards': 'पुरस्कार',
    'games.estimatedTime': 'अनुमानित समय',
    'games.difficulty': 'कठिनाई',
    'games.players': 'खिलाड़ी',
    'games.rating': 'रेटिंग',
    'games.backToGames': '← गेम्स पर वापस',
    
    // Badges Page
    'badges.title': 'बैज संग्रह',
    'badges.subtitle': 'अपनी उपलब्धियों को दिखाएं और विशेष पुरस्कार अनलॉक करें',
    'badges.allBadges': 'सभी बैज',
    'badges.earned': 'अर्जित',
    'badges.locked': 'लॉक्ड',
    'badges.bridgePro': 'BriDGe प्रो',
    'badges.totalBadges': 'कुल बैज',
    'badges.rareBadges': 'दुर्लभ बैज',
    'badges.epicBadges': 'एपिक बैज',
    'badges.legendaryBadges': 'लेजेंडरी बैज',
    'badges.bridgeProBadges': 'BriDGe प्रो बैज',
    'badges.earnedOn': 'अर्जित किया गया',
    'badges.progress': 'प्रगति',
    'badges.xpReward': 'XP पुरस्कार',
    'badges.unlockWithPro': 'BriDGe प्रो के साथ अनलॉक करें',
    'badges.getProAccess': 'प्रो एक्सेस प्राप्त करें',
    'badges.backToBadges': '← बैज पर वापस',
    
    // Profile Sidebar
    'sidebar.profile': 'प्रोफाइल',
    'sidebar.viewProfile': 'प्रोफाइल देखें →',
    'sidebar.computerScienceStudent': '🎓 कंप्यूटर साइंस छात्र',
    'sidebar.quickActions': 'त्वरित कार्य',
    'sidebar.editProfile': 'प्रोफाइल संपादित करें',
    'sidebar.settings': 'सेटिंग्स',
    'sidebar.help': 'सहायता और समर्थन',
    'sidebar.recentActivity': 'हाल की गतिविधि',
    'sidebar.completedCourse': 'रिएक्ट कोर्स पूरा किया',
    'sidebar.earnedBadge': 'कोड मास्टर बैज अर्जित किया',
    'sidebar.joinedTeam': 'हैकाथॉन टीम में शामिल हुए',
    'sidebar.proFeatures': 'प्रो सुविधाएं',
    'sidebar.aiMentor': 'AI मेंटर चैट',
    'sidebar.premiumCourses': 'प्रीमियम कोर्स',
    'sidebar.prioritySupport': 'प्राथमिकता समर्थन',
    'sidebar.upgradeToPro': 'प्रो में अपग्रेड करें',
    'sidebar.profileCompletion': 'प्रोफाइल पूर्णता',
    'sidebar.completeProfile': 'अधिक अवसरों को अनलॉक करने के लिए अपनी प्रोफाइल पूरी करें!',
    'sidebar.completeMyProfile': 'मेरी प्रोफाइल पूरी करें →',
    'sidebar.navigation': 'नेवीगेशन',
    'sidebar.quickActions': 'त्वरित कार्य',
    'sidebar.findJobs': 'नौकरी खोजें',
    'sidebar.findMentors': 'मेंटर खोजें',
    'sidebar.practice': 'अभ्यास',
    'sidebar.badges': 'बैज',
    'sidebar.recentActivity': 'हाल की गतिविधि',
    'sidebar.appliedToGoogle': 'Google इंटर्नशिप के लिए आवेदन किया',
    'sidebar.earnedCodeMaster': 'कोड मास्टर बैज अर्जित किया',
    'sidebar.completedReact': 'React कोर्स पूरा किया',
    'sidebar.hoursAgo': 'घंटे पहले',
    'sidebar.dayAgo': 'दिन पहले',
    'sidebar.daysAgo': 'दिन पहले',
    'sidebar.bridgeProFeatures': 'Bridge Pro सुविधाएं',
    'sidebar.aiCareerGuidance': 'AI करियर मार्गदर्शन',
    'sidebar.getPersonalizedAdvice': 'व्यक्तिगत करियर सलाह प्राप्त करें',
    'sidebar.priorityApplications': 'प्राथमिकता आवेदन',
    'sidebar.skipQueue': 'प्राथमिकता के साथ कतार छोड़ें',
    'sidebar.advancedAnalytics': 'उन्नत एनालिटिक्स',
    'sidebar.detailedInsights': 'विस्तृत प्रदर्शन अंतर्दृष्टि',
    'sidebar.settings': 'सेटिंग्स',
    'sidebar.logout': 'लॉगआउट',
    'sidebar.gamesAndPractice': 'गेम्स और अभ्यास',
    'sidebar.badgesAndAchievements': 'बैज और उपलब्धियां',
    
    // AI Pro Page
    'aipro.title': 'BriDGe AI प्रो',
    'aipro.subtitle': 'उन्नत AI-संचालित उपकरणों और अंतर्दृष्टि के साथ अपने करियर को सुपरचार्ज करें',
    'aipro.aiRecommendations': 'AI सिफारिशें',
    'aipro.successRate': 'सफलता दर',
    'aipro.aiAssistant': 'AI सहायक',
    'aipro.aiPoweredFeatures': '🚀 AI-संचालित सुविधाएं',
    'aipro.chooseYourPlan': '💎 अपना AI प्रो प्लान चुनें',
    'aipro.successStories': '🌟 सफलता की कहानियां',
    'aipro.mostPopular': 'सबसे लोकप्रिय',
    'aipro.startFreeTrial': 'मुफ्त ट्रायल शुरू करें',
    'aipro.getStarted': 'शुरू करें',
    'aipro.careerGuidance': 'AI करियर मार्गदर्शन',
    'aipro.careerGuidanceDesc': 'उन्नत मशीन लर्निंग द्वारा संचालित व्यक्तिगत करियर सिफारिशें प्राप्त करें',
    'aipro.smartMatching': 'स्मार्ट जॉब मैचिंग',
    'aipro.smartMatchingDesc': 'आपकी प्रोफाइल के आधार पर 95% सटीकता के साथ AI-संचालित जॉब सिफारिशें',
    'aipro.skillAnalysis': 'स्किल गैप एनालिसिस',
    'aipro.skillAnalysisDesc': 'बाजार की मांग बनाम आपके कौशल का उन्नत AI विश्लेषण',
    'aipro.interviewCoach': 'AI इंटरव्यू कोच',
    'aipro.interviewCoachDesc': 'AI इंटरव्यूअर के साथ अभ्यास करें और रियल-टाइम फीडबैक प्राप्त करें',
    'aipro.resumeOptimizer': 'रिज्यूमे AI ऑप्टिमाइज़र',
    'aipro.resumeOptimizerDesc': 'ATS ऑप्टिमाइज़ेशन के साथ AI-संचालित रिज्यूमे विश्लेषण',
    'aipro.marketInsights': 'AI मार्केट इनसाइट्स',
    'aipro.marketInsightsDesc': 'रियल-टाइम मार्केट विश्लेषण और वेतन पूर्वानुमान',
    'aipro.mentorMatching': 'AI मेंटर मैचिंग',
    'aipro.mentorMatchingDesc': 'AI संगतता विश्लेषण का उपयोग करके परफेक्ट मेंटर खोजें',
    'aipro.personalizedLearning': 'व्यक्तिगत शिक्षा',
    'aipro.personalizedLearningDesc': 'आपके करियर लक्ष्यों के आधार पर AI-क्यूरेटेड लर्निंग पाथ',
    'aipro.salaryNegotiator': 'AI सैलरी नेगोसिएटर',
    'aipro.salaryNegotiatorDesc': 'AI-संचालित वेतन वार्ता रणनीतियां और बाजार डेटा',
    'aipro.networkBuilder': 'AI नेटवर्क बिल्डर',
    'aipro.networkBuilderDesc': 'स्मार्ट नेटवर्किंग सिफारिशें और कनेक्शन रणनीतियां',
    'aipro.careerPredictor': 'करियर पाथ प्रेडिक्टर',
    'aipro.careerPredictorDesc': 'आपके करियर ट्रैजेक्टरी और अवसरों के लिए AI पूर्वानुमान',
    'aipro.portfolioBuilder': 'AI पोर्टफोलियो बिल्डर',
    'aipro.portfolioBuilderDesc': 'AI-जेनेरेटेड कंटेंट और डिज़ाइन के साथ शानदार पोर्टफोलियो बनाएं',
    
    // Common Sections
    'common.internships': 'इंटर्नशिप',
    'common.networking': 'नेटवर्किंग',
    'common.mockPractice': 'मॉक अभ्यास',
    'common.applyNow': 'अभी आवेदन करें',
    'common.learnMore': 'और जानें',
    'common.viewAll': 'सभी देखें',
    
    // Networking Section
    'networking.title': 'कनेक्ट और नेटवर्क',
    'networking.mentors': 'मेंटर्स',
    'networking.alumni': 'पूर्व छात्र',
    'networking.peers': 'साथी',
    'networking.connectNow': 'अभी कनेक्ट करें',
    'networking.bookSession': 'सत्र बुक करें',
    'networking.sendMessage': 'संदेश भेजें',
    'networking.years': 'वर्ष',
    'networking.sessions': 'सत्र',
    
    // Mock Practice Section
    'mockPractice.title': 'मॉक अभ्यास और इंटरव्यू',
    'mockPractice.technicalInterview': 'तकनीकी इंटरव्यू',
    'mockPractice.behavioralInterview': 'व्यवहारिक इंटरव्यू',
    'mockPractice.caseStudy': 'केस स्टडी',
    'mockPractice.startPractice': 'अभ्यास शुरू करें',
    'mockPractice.difficulty': 'कठिनाई',
    'mockPractice.duration': 'अवधि',
    'mockPractice.earnBadges': 'बैज अर्जित करें',
    'mockPractice.unlockAchievements': 'चुनौतियों को पूरा करते समय उपलब्धियों को अनलॉक करें',
    
    // Games Content
    'games.logicLoop': 'LogicLoop',
    'games.careerXP': 'CareerXP',
    'games.logicCoding': 'लॉजिक और कोडिंग',
    'games.careerSimulation': 'करियर सिमुलेशन',
    'games.intermediate': 'मध्यम',
    'games.beginner': 'शुरुआती',
    'games.advanced': 'उन्नत',
    'games.minPerSession': 'मिनट प्रति सत्र',
    'games.minPerChallenge': 'मिनट प्रति चुनौती',
    'games.masterCoding': 'इंटरैक्टिव MCQ चुनौतियों के माध्यम से कोडिंग लॉजिक में महारत हासिल करें जो आपके समस्या-समाधान कौशल का परीक्षण करती हैं।',
    'games.progressAlgorithmic': 'एल्गोरिदमिक पहेलियों, डेटा स्ट्रक्चर प्रश्नों और प्रोग्रामिंग अवधारणाओं के माध्यम से प्रगति करें।',
    'games.competeRealTime': 'रियल-टाइम लॉजिक बैटल में साथियों के साथ प्रतिस्पर्धा करें और ग्लोबल लीडरबोर्ड पर चढ़ें।',
    'games.unlockAdvanced': 'डायनामिक प्रोग्रामिंग, ग्राफ थ्योरी और सिस्टम डिज़ाइन जैसे उन्नत विषयों को अनलॉक करें।',
    'games.createAvatar': 'अपना पेशेवर अवतार बनाएं और वास्तविक करियर चुनौतियों पर निकलें।',
    'games.buildResumes': 'रिज्यूमे बनाएं, उद्योग की पहेलियों को हल करें, और इमर्सिव परिदृश्यों में मिनी-इंटरव्यू का अभ्यास करें।',
    'games.progressJobRoles': 'विभिन्न नौकरी भूमिकाओं के माध्यम से प्रगति करें और वास्तविक कंपनियों पर आधारित करियर कहानियों को अनलॉक करें।',
    'games.earnBadgesPoints': 'स्तरों के माध्यम से आगे बढ़ते समय बैज, स्किल पॉइंट्स और मेंटरशिप के अवसर अर्जित करें।',
    'games.moreInfo': 'अधिक जानकारी',
    'games.badgesEarned': 'अर्जित बैज',
    'games.inProgress': 'प्रगति में',
    'games.completionRate': 'पूर्णता दर',
    'games.earnedBadges': 'अर्जित बैज',
    
    // Badge Names and Descriptions
    'badges.codeMaster': 'कोड मास्टर',
    'badges.codeMasterDesc': '50 कोडिंग चुनौतियां पूरी करें',
    'badges.aiExplorer': 'AI एक्सप्लोरर',
    'badges.aiExplorerDesc': 'AI लर्निंग पाथ पूरा करें',
    'badges.quickLearner': 'त्वरित शिक्षार्थी',
    'badges.quickLearnerDesc': 'रिकॉर्ड समय में कोर्स पूरे करें',
    'badges.profilePro': 'प्रोफाइल प्रो',
    'badges.profileProDesc': 'अपनी प्रोफाइल 100% पूरी करें',
    'badges.legendary': 'लेजेंडरी',
    'badges.epic': 'एपिक',
    'badges.rare': 'दुर्लभ',
    'badges.common': 'सामान्य',
    
    // Mentor Events
    'mentorEvents.resumeReview': 'प्रिया के साथ रिज्यूमे समीक्षा',
    'mentorEvents.systemDesign': 'आकाश के साथ सिस्टम डिज़ाइन मास्टरक्लास',
    'mentorEvents.aiCareerGuidance': 'AI करियर मार्गदर्शन सत्र',
    'mentorEvents.joinButton': 'शामिल हों',
    'mentorEvents.viewAllEvents': 'सभी इवेंट्स देखें',
    
    // Language Selector
    'language.english': 'English',
    'language.hindi': 'हिंदी',
    'language.odia': 'ଓଡ଼ିଆ'
  },
  
  or: {
    // Header
    'header.logo': 'BriDGe',
    'header.search': 'ସୁଯୋଗ, ପାଠ୍ୟକ୍ରମ, ମେଣ୍ଟର ଖୋଜନ୍ତୁ...',
    'header.opportunities': 'ସୁଯୋଗ',
    'header.mentors': 'ମେଣ୍ଟର',
    'header.games': 'ଖେଳ',
    'header.badges': 'ବ୍ୟାଜ୍',
    'header.aipro': 'AI ପ୍ରୋ',
    'header.profile': 'ପ୍ରୋଫାଇଲ୍',
    
    // Home Page
    'home.hero.title': 'ଫାଙ୍କ ପୂରଣ କରନ୍ତୁ, ଭବିଷ୍ୟତ ଗଢ଼ନ୍ତୁ',
    'home.hero.subtitle': 'ଆପଣଙ୍କ କ୍ୟାରିୟର ଯାତ୍ରାକୁ ତ୍ୱରାନ୍ୱିତ କରିବା ପାଇଁ ସୁଯୋଗ, ମେଣ୍ଟର ଏବଂ ସମ୍ବଳ ସହିତ ସଂଯୁକ୍ତ ହୁଅନ୍ତୁ',
    'home.hero.getStarted': 'ଆରମ୍ଭ କରନ୍ତୁ',
    'home.hero.learnMore': 'ଅଧିକ ଜାଣନ୍ତୁ',
    'home.stats.opportunities': 'ସୁଯୋଗ',
    'home.stats.mentors': 'ମେଣ୍ଟର',
    'home.stats.students': 'ଛାତ୍ର',
    
    // Profile
    'profile.title': 'ପ୍ରୋଫାଇଲ୍',
    'profile.viewProfile': 'ପ୍ରୋଫାଇଲ୍ ଦେଖନ୍ତୁ →',
    'profile.personalInfo': 'ବ୍ୟକ୍ତିଗତ ସୂଚନା',
    'profile.education': 'ଶିକ୍ଷା',
    'profile.skills': 'କୌଶଳ ଏବଂ ଭାଷା',
    'profile.experience': 'ଅଭିଜ୍ଞତା ଏବଂ ପ୍ରକଳ୍ପ',
    'profile.additional': 'ଅତିରିକ୍ତ ସୂଚନା',
    'profile.save': 'ପରିବର୍ତ୍ତନ ସଂରକ୍ଷଣ କରନ୍ତୁ',
    'profile.preview': 'ପ୍ରୋଫାଇଲ୍ ପୂର୍ବାବଲୋକନ',
    'profile.profileViews': 'ପ୍ରୋଫାଇଲ୍ ଦୃଶ୍ୟ',
    'profile.achievements': 'ସଫଳତା',
    'profile.currentLevel': 'ବର୍ତ୍ତମାନ ସ୍ତର',
    'profile.skillsExpertise': 'କୌଶଳ ଏବଂ ବିଶେଷଜ୍ଞତା',
    'profile.achievementsBadges': 'ସଫଳତା ଏବଂ ବ୍ୟାଜ୍',
    'profile.recentActivity': 'ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ',
    'profile.viewAllBadges': 'ସମସ୍ତ ବ୍ୟାଜ୍ ଦେଖନ୍ତୁ',
    'profile.email': 'ଇମେଲ୍',
    'profile.location': 'ସ୍ଥାନ',
    'profile.university': 'ବିଶ୍ୱବିଦ୍ୟାଳୟ',
    'profile.graduationYear': 'ସ୍ନାତକ ବର୍ଷ',
    'profile.earned': 'ଅର୍ଜିତ',
    'profile.inProgress': 'ପ୍ରଗତିରେ',
    'profile.completedCourse': 'ରିଆକ୍ଟ କୋର୍ସ ସମ୍ପୂର୍ଣ୍ଣ କଲେ',
    'profile.earnedBadge': 'କୋଡ୍ ମାଷ୍ଟର ବ୍ୟାଜ୍ ଅର୍ଜନ କଲେ',
    'profile.joinedTeam': 'ହ୍ୟାକାଥନ୍ ଟିମରେ ଯୋଗ ଦେଲେ',
    'profile.updatedProfile': 'ପ୍ରୋଫାଇଲ୍ ଅପଡେଟ୍ କଲେ',
    'profile.hoursAgo': 'ଘଣ୍ଟା ପୂର୍ବେ',
    'profile.dayAgo': 'ଦିନ ପୂର୍ବେ',
    'profile.daysAgo': 'ଦିନ ପୂର୍ବେ',
    'profile.weekAgo': 'ସପ୍ତାହ ପୂର୍ବେ',
    
    // Profile Edit
    'profileEdit.personalInfo.title': 'ବ୍ୟକ୍ତିଗତ ସୂଚନା',
    'profileEdit.firstName': 'ପ୍ରଥମ ନାମ',
    'profileEdit.lastName': 'ଶେଷ ନାମ',
    'profileEdit.email': 'ଇମେଲ୍ ଠିକଣା',
    'profileEdit.phone': 'ଫୋନ୍ ନମ୍ବର',
    'profileEdit.dateOfBirth': 'ଜନ୍ମ ତାରିଖ',
    'profileEdit.gender': 'ଲିଙ୍ଗ',
    'profileEdit.nationality': 'ଜାତୀୟତା',
    'profileEdit.location': 'ବର୍ତ୍ତମାନ ସ୍ଥାନ',
    'profileEdit.address': 'ସମ୍ପୂର୍ଣ୍ଣ ଠିକଣା',
    'profileEdit.bio': 'ବାୟୋ / ନିଜ ବିଷୟରେ',
    'profileEdit.socialLinks': 'ସାମାଜିକ ଲିଙ୍କ',
    'profileEdit.linkedin': 'ଲିଙ୍କଡଇନ୍ ପ୍ରୋଫାଇଲ୍',
    'profileEdit.github': 'ଗିଟହବ୍ ପ୍ରୋଫାଇଲ୍',
    'profileEdit.portfolio': 'ପୋର୍ଟଫୋଲିଓ ୱେବସାଇଟ୍',
    
    // Education
    'education.title': 'ଶିକ୍ଷା ବିବରଣୀ',
    'education.current': 'ବର୍ତ୍ତମାନ ଶିକ୍ଷା',
    'education.previous': 'ପୂର୍ବ ଶିକ୍ଷା',
    'education.institution': 'ଅନୁଷ୍ଠାନର ନାମ',
    'education.degree': 'ଡିଗ୍ରୀ',
    'education.field': 'ଅଧ୍ୟୟନ କ୍ଷେତ୍ର',
    'education.semester': 'ବର୍ତ୍ତମାନ ସେମିଷ୍ଟର',
    'education.cgpa': 'ବର୍ତ୍ତମାନ CGPA / ଶତକଡ଼ା',
    'education.startYear': 'ଆରମ୍ଭ ବର୍ଷ',
    'education.endYear': 'ଆଶା କରାଯାଉଥିବା ଶେଷ ବର୍ଷ',
    'education.addEducation': '+ ଶିକ୍ଷା ଯୋଗ କରନ୍ତୁ',
    'education.removeEducation': 'ଶିକ୍ଷା ହଟାନ୍ତୁ',
    
    // Skills
    'skills.title': 'କୌଶଳ ଏବଂ ଭାଷା',
    'skills.technical': 'ବୈଷୟିକ କୌଶଳ',
    'skills.soft': 'ସଫ୍ଟ ସ୍କିଲ୍',
    'skills.languages': 'ଜଣାଥିବା ଭାଷା',
    'skills.addTechnical': 'ବୈଷୟିକ କୌଶଳ ଯୋଗ କରନ୍ତୁ ଏବଂ ଏଣ୍ଟର ଦବାନ୍ତୁ',
    'skills.addSoft': 'ସଫ୍ଟ ସ୍କିଲ୍ ଯୋଗ କରନ୍ତୁ ଏବଂ ଏଣ୍ଟର ଦବାନ୍ତୁ',
    'skills.addLanguage': 'ଭାଷା ଯୋଗ କରନ୍ତୁ ଏବଂ ଏଣ୍ଟର ଦବାନ୍ତୁ',
    
    // Experience
    'experience.title': 'ଅଭିଜ୍ଞତା ଏବଂ ପ୍ରକଳ୍ପ',
    'experience.work': 'କାର୍ଯ୍ୟ ଅଭିଜ୍ଞତା',
    'experience.projects': 'ପ୍ରକଳ୍ପଗୁଡ଼ିକ',
    'experience.company': 'କମ୍ପାନୀ',
    'experience.position': 'ପଦବୀ',
    'experience.startDate': 'ଆରମ୍ଭ ତାରିଖ',
    'experience.endDate': 'ଶେଷ ତାରିଖ',
    'experience.description': 'ବର୍ଣ୍ଣନା',
    'experience.addExperience': '+ ଅଭିଜ୍ଞତା ଯୋଗ କରନ୍ତୁ',
    'experience.addProject': '+ ପ୍ରକଳ୍ପ ଯୋଗ କରନ୍ତୁ',
    'experience.projectName': 'ପ୍ରକଳ୍ପର ନାମ',
    'experience.projectLink': 'ପ୍ରକଳ୍ପ ଲିଙ୍କ',
    'experience.remove': 'ହଟାନ୍ତୁ',
    
    // Additional Info
    'additional.title': 'ଅତିରିକ୍ତ ସୂଚନା',
    'additional.achievements': 'ସଫଳତା ଏବଂ ପୁରସ୍କାର',
    'additional.extracurricular': 'ପାଠ୍ୟକ୍ରମ ବାହାରେ କାର୍ଯ୍ୟକଳାପ',
    'additional.careerGoals': 'କ୍ୟାରିୟର ଲକ୍ଷ୍ୟ ଏବଂ ଆଗ୍ରହ',
    'additional.jobRoles': 'ପସନ୍ଦର ଚାକିରି ଭୂମିକା',
    'additional.salary': 'ଆଶା କରାଯାଉଥିବା ବେତନ ସୀମା',
    
    // Common
    'common.backToProfile': '← ପ୍ରୋଫାଇଲ୍କୁ ଫେରନ୍ତୁ',
    'common.male': 'ପୁରୁଷ',
    'common.female': 'ମହିଳା',
    'common.other': 'ଅନ୍ୟ',
    'common.preferNotToSay': 'କହିବାକୁ ଚାହୁଁନାହିଁ',
    'common.required': '*',
    
    // Featured Updates
    'featured.title': 'ବିଶେଷ ଅପଡେଟ୍',
    'featured.subtitle': 'ନୂତନ ସୁଯୋଗ ଏବଂ ସମ୍ବାଦ ସହିତ ଅପଡେଟ୍ ରୁହନ୍ତୁ',
    'featured.aiTool.title': 'ନୂତନ AI-ଚାଳିତ କ୍ୟାରିୟର ମାର୍ଗଦର୍ଶନ ଉପକରଣ ଲଞ୍ଚ',
    'featured.aiTool.description': 'ଆମର ନୂତନ AI ଟେକ୍ନୋଲୋଜି ସହିତ ବ୍ୟକ୍ତିଗତ କ୍ୟାରିୟର ସୁପାରିଶ ପାଆନ୍ତୁ',
    'featured.gsoc.title': 'Google Summer of Code 2024 ଆବେଦନ ଖୋଲା',
    'featured.gsoc.description': 'ଶୀର୍ଷ ଟେକ୍ କମ୍ପାନୀଗୁଡ଼ିକ ସହିତ ରୋମାଞ୍ଚକର ଓପନ୍ ସୋର୍ସ ପ୍ରକଳ୍ପ ପାଇଁ ଏବେ ଆବେଦନ କରନ୍ତୁ',
    'featured.partnership.title': 'ଶୀର୍ଷ ବିଶ୍ୱବିଦ୍ୟାଳୟ ସହିତ ନୂତନ ସହଯୋଗିତା',
    'featured.partnership.description': 'ଅଗ୍ରଣୀ ଅନୁଷ୍ଠାନଗୁଡ଼ିକରୁ ବିଶେଷ ପାଠ୍ୟକ୍ରମ ଏବଂ ମେଣ୍ଟରସିପ୍ ପାଇବେ',
    'featured.productUpdate': 'ଉତ୍ପାଦ ଅପଡେଟ୍',
    'featured.opportunity': 'ସୁଯୋଗ',
    'featured.partnershipCategory': 'ସହଯୋଗିତା',
    
    // Jobs Section
    'jobs.title': 'ଚାକିରି ସୁଯୋଗ',
    'jobs.availableJobs': 'ଉପଲବ୍ଧ ଚାକିରି',
    'jobs.recommendedJobs': 'ସୁପାରିଶ କରାଯାଇଥିବା ଚାକିରି',
    'jobs.match': 'ମ୍ୟାଚ୍',
    'jobs.applyNow': 'ଏବେ ଆବେଦନ କରନ୍ତୁ',
    'jobs.fullTime': 'ପୂର୍ଣ୍ଣକାଳୀନ',
    'jobs.partTime': 'ଅଂଶକାଳୀନ',
    'jobs.remote': 'ରିମୋଟ୍',
    
    // Courses Section
    'courses.title': 'ଶିକ୍ଷଣ ପାଠ୍ୟକ୍ରମ',
    'courses.youtube': 'YouTube ପାଠ୍ୟକ୍ରମ',
    'courses.coursera': 'Coursera ପାଠ୍ୟକ୍ରମ',
    'courses.enrollNow': 'ଏବେ ନାମ ଲେଖାନ୍ତୁ',
    'courses.certificate': 'ପ୍ରମାଣପତ୍ର',
    'courses.students': 'ଛାତ୍ର',
    'courses.hours': 'ଘଣ୍ଟା',
    'courses.months': 'ମାସ',
    
    // Opportunities Page
    'opportunities.title': 'ସୁଯୋଗ ଖୋଜନ୍ତୁ',
    'opportunities.subtitle': 'ଆପଣଙ୍କ କ୍ୟାରିୟରକୁ ତ୍ୱରାନ୍ୱିତ କରିବା ପାଇଁ ହଜାରେ ଚାକିରି, ଇଣ୍ଟର୍ନସିପ୍, ହ୍ୟାକାଥନ୍ ଏବଂ ପ୍ରତିଯୋଗିତାର ଅନ୍ୱେଷଣ କରନ୍ତୁ',
    'opportunities.allOpportunities': 'ସମସ୍ତ ସୁଯୋଗ',
    'opportunities.jobs': 'ଚାକିରି',
    'opportunities.internships': 'ଇଣ୍ଟର୍ନସିପ୍',
    'opportunities.hackathons': 'ହ୍ୟାକାଥନ୍',
    'opportunities.competitions': 'ପ୍ରତିଯୋଗିତା',
    'opportunities.found': 'ସୁଯୋଗ ମିଳିଲା',
    'opportunities.totalApplicants': 'ମୋଟ ଆବେଦନକାରୀ',
    'opportunities.deadline': 'ଶେଷ ତାରିଖ',
    'opportunities.requiredSkills': 'ଆବଶ୍ୟକ କୌଶଳ',
    'opportunities.applied': 'ଆବେଦନ କଲେ',
    'opportunities.applyNow': 'ଏବେ ଆବେଦନ କରନ୍ତୁ',
    'opportunities.job': 'ଚାକିରି',
    'opportunities.internship': 'ଇଣ୍ଟର୍ନସିପ୍',
    'opportunities.hackathon': 'ହ୍ୟାକାଥନ୍',
    'opportunities.competition': 'ପ୍ରତିଯୋଗିତା',
    
    // Mentors Page
    'mentors.title': 'ମେଣ୍ଟରମାନଙ୍କ ସହିତ ସଂଯୋଗ କରନ୍ତୁ',
    'mentors.subtitle': 'ଶିଳ୍ପ ନେତା, ପୂର୍ବତନ ଛାତ୍ର ଏବଂ ଭବିଷ୍ୟତ ଗଢ଼ୁଥିବା ପେଶାଦାରଙ୍କଠାରୁ ସିଧାସଳଖ ଶିଖନ୍ତୁ।',
    'mentors.intro': 'ଆପଣ କ୍ୟାରିୟର ପଥ ଅନ୍ୱେଷଣ କରୁଥିବେ, ଇଣ୍ଟରଭ୍ୟୁ ପାଇଁ ପ୍ରସ୍ତୁତି କରୁଥିବେ, କିମ୍ବା ବାସ୍ତବ ଦୁନିଆର ପ୍ରକଳ୍ପ ନିର୍ମାଣ କରୁଥିବେ — ସେହି ମେଣ୍ଟରମାନଙ୍କ ସହିତ ସଂଯୋଗ କରନ୍ତୁ ଯେଉଁମାନେ ସେଠାରେ ଅଛନ୍ତି। ବ୍ୟକ୍ତିଗତ ମାର୍ଗଦର୍ଶନ, କ୍ୟାରିୟର ଅନ୍ତର୍ଦୃଷ୍ଟି ଏବଂ ନେଟୱାର୍କିଂ ସୁଯୋଗ ପାଆନ୍ତୁ।',
    'mentors.searchPlaceholder': 'କୌଶଳ, କମ୍ପାନୀ କିମ୍ବା ଡୋମେନ୍ ଦ୍ୱାରା ମେଣ୍ଟର ଖୋଜନ୍ତୁ...',
    'mentors.allMentors': 'ସମସ୍ତ ମେଣ୍ଟର',
    'mentors.techDevelopment': 'ଟେକ୍ ଏବଂ ଡେଭଲପମେଣ୍ଟ',
    'mentors.dataScience': 'ଡାଟା ସାଇନ୍ସ ଏବଂ AI',
    'mentors.careerSkills': 'କ୍ୟାରିୟର ଏବଂ ସଫ୍ଟ ସ୍କିଲ୍',
    'mentors.designCreativity': 'ଡିଜାଇନ୍ ଏବଂ ସୃଜନଶୀଳତା',
    'mentors.entrepreneurship': 'ଉଦ୍ୟୋଗ',
    'mentors.alumni': 'ପୂର୍ବତନ ଛାତ୍ର ମେଣ୍ଟର',
    'mentors.available': 'ଉପଲବ୍ଧ ମେଣ୍ଟର',
    'mentors.totalSessions': 'ମୋଟ ସେସନ୍',
    'mentors.aiRecommendation': 'AI ମେଣ୍ଟର ସୁପାରିଶ',
    'mentors.basedOnInterests': 'ମେସିନ୍ ଲର୍ନିଂରେ ଆପଣଙ୍କ ଆଗ୍ରହ ଆଧାରରେ:',
    'mentors.connect': 'ସଂଯୋଗ କରନ୍ତୁ',
    'mentors.upcomingEvents': 'ଆଗାମୀ ମେଣ୍ଟର ଇଭେଣ୍ଟ',
    'mentors.joinLiveSessions': 'ପ୍ରତି ସପ୍ତାହାନ୍ତରେ ଲାଇଭ ମେଣ୍ଟର ସେସନରେ ଯୋଗ ଦିଅନ୍ତୁ।',
    'mentors.join': 'ଯୋଗ ଦିଅନ୍ତୁ',
    'mentors.viewAllEvents': 'ସମସ୍ତ ଇଭେଣ୍ଟ ଦେଖନ୍ତୁ →',
    'mentors.expertise': 'ବିଶେଷଜ୍ଞତା',
    'mentors.availability': 'ଉପଲବ୍ଧତା',
    'mentors.sessions': 'ସେସନ୍',
    'mentors.completed': 'ସମ୍ପୂର୍ଣ୍ଣ',
    'mentors.experience': 'ଅଭିଜ୍ଞତା',
    'mentors.bookSession': 'ସେସନ୍ ବୁକ୍ କରନ୍ତୁ',
    'mentors.viewProfile': 'ପ୍ରୋଫାଇଲ୍ ଦେଖନ୍ତୁ',
    'mentors.message': 'ସନ୍ଦେଶ',
    'mentors.quote1': 'ମହାନ ମେଣ୍ଟରସିପ୍ ସମ୍ଭାବନାକୁ ପ୍ରଦର୍ଶନରେ ପରିଣତ କରେ।',
    'mentors.quote2': 'ପ୍ରତ୍ୟେକ ସେତୁ ଏକ ମେଣ୍ଟରଠାରୁ ଆରମ୍ଭ ହୁଏ ଯିଏ ପ୍ରଥମ ପାଦକ୍ଷେପ ଦେଖାଏ।',
    
    // Games Page
    'games.title': 'ଆପଣଙ୍କ କୌଶଳ ବୃଦ୍ଧି କରନ୍ତୁ',
    'games.subtitle': 'ଇଣ୍ଟରାକ୍ଟିଭ ଗେମ୍, ଚ୍ୟାଲେଞ୍ଜ ଏବଂ ସିମୁଲେସନ୍ ମାଧ୍ୟମରେ ଆପଣଙ୍କ କ୍ୟାରିୟରରେ ଦକ୍ଷତା ହାସଲ କରନ୍ତୁ',
    'games.gamesPlayed': 'ଖେଳାଯାଇଥିବା ଗେମ୍',
    'games.skillPoints': 'ସ୍କିଲ୍ ପଏଣ୍ଟ',
    'games.badges': 'ବ୍ୟାଜ୍',
    'games.level': 'ସ୍ତର',
    'games.playNow': 'ଏବେ ଖେଳନ୍ତୁ',
    'games.learnMore': 'ଅଧିକ ଜାଣନ୍ତୁ',
    'games.achievements': 'ଆପଣଙ୍କ ସଫଳତା',
    'games.leaderboard': 'ଗ୍ଲୋବାଲ୍ ଲିଡରବୋର୍ଡ',
    'games.features': 'ବିଶେଷତା',
    'games.rewards': 'ପୁରସ୍କାର',
    'games.estimatedTime': 'ଆନୁମାନିକ ସମୟ',
    'games.difficulty': 'କଠିନତା',
    'games.players': 'ଖେଳାଳି',
    'games.rating': 'ରେଟିଂ',
    'games.backToGames': '← ଗେମ୍ସକୁ ଫେରନ୍ତୁ',
    
    // Badges Page
    'badges.title': 'ବ୍ୟାଜ୍ ସଂଗ୍ରହ',
    'badges.subtitle': 'ଆପଣଙ୍କ ସଫଳତା ପ୍ରଦର୍ଶନ କରନ୍ତୁ ଏବଂ ବିଶେଷ ପୁରସ୍କାର ଅନଲକ୍ କରନ୍ତୁ',
    'badges.allBadges': 'ସମସ୍ତ ବ୍ୟାଜ୍',
    'badges.earned': 'ଅର୍ଜିତ',
    'badges.locked': 'ଲକ୍ ହୋଇଛି',
    'badges.bridgePro': 'BriDGe ପ୍ରୋ',
    'badges.totalBadges': 'ମୋଟ ବ୍ୟାଜ୍',
    'badges.rareBadges': 'ବିରଳ ବ୍ୟାଜ୍',
    'badges.epicBadges': 'ଏପିକ୍ ବ୍ୟାଜ୍',
    'badges.legendaryBadges': 'କିମ୍ବଦନ୍ତୀ ବ୍ୟାଜ୍',
    'badges.bridgeProBadges': 'BriDGe ପ୍ରୋ ବ୍ୟାଜ୍',
    'badges.earnedOn': 'ଅର୍ଜନ କରାଯାଇଛି',
    'badges.progress': 'ପ୍ରଗତି',
    'badges.xpReward': 'XP ପୁରସ୍କାର',
    'badges.unlockWithPro': 'BriDGe ପ୍ରୋ ସହିତ ଅନଲକ୍ କରନ୍ତୁ',
    'badges.getProAccess': 'ପ୍ରୋ ଆକ୍ସେସ୍ ପାଆନ୍ତୁ',
    'badges.backToBadges': '← ବ୍ୟାଜ୍କୁ ଫେରନ୍ତୁ',
    
    // Profile Sidebar
    'sidebar.profile': 'ପ୍ରୋଫାଇଲ୍',
    'sidebar.viewProfile': 'ପ୍ରୋଫାଇଲ୍ ଦେଖନ୍ତୁ →',
    'sidebar.computerScienceStudent': '🎓 କମ୍ପ୍ୟୁଟର ସାଇନ୍ସ ଛାତ୍ର',
    'sidebar.quickActions': 'ତ୍ୱରିତ କାର୍ଯ୍ୟ',
    'sidebar.editProfile': 'ପ୍ରୋଫାଇଲ୍ ସମ୍ପାଦନା କରନ୍ତୁ',
    'sidebar.settings': 'ସେଟିଂସ୍',
    'sidebar.help': 'ସାହାଯ୍ୟ ଏବଂ ସମର୍ଥନ',
    'sidebar.recentActivity': 'ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ',
    'sidebar.completedCourse': 'ରିଆକ୍ଟ କୋର୍ସ ସମ୍ପୂର୍ଣ୍ଣ କଲେ',
    'sidebar.earnedBadge': 'କୋଡ୍ ମାଷ୍ଟର ବ୍ୟାଜ୍ ଅର୍ଜନ କଲେ',
    'sidebar.joinedTeam': 'ହ୍ୟାକାଥନ୍ ଟିମରେ ଯୋଗ ଦେଲେ',
    'sidebar.proFeatures': 'ପ୍ରୋ ବିଶେଷତା',
    'sidebar.aiMentor': 'AI ମେଣ୍ଟର ଚାଟ୍',
    'sidebar.premiumCourses': 'ପ୍ରିମିୟମ୍ କୋର୍ସ',
    'sidebar.prioritySupport': 'ପ୍ରାଥମିକତା ସମର୍ଥନ',
    'sidebar.upgradeToPro': 'ପ୍ରୋରେ ଅପଗ୍ରେଡ୍ କରନ୍ତୁ',
    'sidebar.profileCompletion': 'ପ୍ରୋଫାଇଲ୍ ସମ୍ପୂର୍ଣ୍ଣତା',
    'sidebar.completeProfile': 'ଅଧିକ ସୁଯୋଗ ଅନଲକ୍ କରିବା ପାଇଁ ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ!',
    'sidebar.completeMyProfile': 'ମୋ ପ୍ରୋଫାଇଲ୍ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ →',
    'sidebar.navigation': 'ନେଭିଗେସନ୍',
    'sidebar.quickActions': 'ତ୍ୱରିତ କାର୍ଯ୍ୟ',
    'sidebar.findJobs': 'ଚାକିରି ଖୋଜନ୍ତୁ',
    'sidebar.findMentors': 'ମେଣ୍ଟର ଖୋଜନ୍ତୁ',
    'sidebar.practice': 'ଅଭ୍ୟାସ',
    'sidebar.badges': 'ବ୍ୟାଜ୍',
    'sidebar.recentActivity': 'ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ',
    'sidebar.appliedToGoogle': 'Google ଇଣ୍ଟର୍ନସିପ୍ ପାଇଁ ଆବେଦନ କଲେ',
    'sidebar.earnedCodeMaster': 'କୋଡ୍ ମାଷ୍ଟର ବ୍ୟାଜ୍ ଅର୍ଜନ କଲେ',
    'sidebar.completedReact': 'React କୋର୍ସ ସମ୍ପୂର୍ଣ୍ଣ କଲେ',
    'sidebar.hoursAgo': 'ଘଣ୍ଟା ପୂର୍ବେ',
    'sidebar.dayAgo': 'ଦିନ ପୂର୍ବେ',
    'sidebar.daysAgo': 'ଦିନ ପୂର୍ବେ',
    'sidebar.bridgeProFeatures': 'Bridge Pro ବିଶେଷତା',
    'sidebar.aiCareerGuidance': 'AI କ୍ୟାରିୟର ମାର୍ଗଦର୍ଶନ',
    'sidebar.getPersonalizedAdvice': 'ବ୍ୟକ୍ତିଗତ କ୍ୟାରିୟର ପରାମର୍ଶ ପାଆନ୍ତୁ',
    'sidebar.priorityApplications': 'ପ୍ରାଥମିକତା ଆବେଦନ',
    'sidebar.skipQueue': 'ପ୍ରାଥମିକତା ସହିତ ଧାଡ଼ି ଛାଡ଼ନ୍ତୁ',
    'sidebar.advancedAnalytics': 'ଉନ୍ନତ ଆନାଲିଟିକ୍ସ',
    'sidebar.detailedInsights': 'ବିସ୍ତୃତ ପ୍ରଦର୍ଶନ ଅନ୍ତର୍ଦୃଷ୍ଟି',
    'sidebar.settings': 'ସେଟିଂସ୍',
    'sidebar.logout': 'ଲଗଆଉଟ୍',
    'sidebar.gamesAndPractice': 'ଗେମ୍ ଏବଂ ଅଭ୍ୟାସ',
    'sidebar.badgesAndAchievements': 'ବ୍ୟାଜ୍ ଏବଂ ସଫଳତା',
    
    // AI Pro Page
    'aipro.title': 'BriDGe AI ପ୍ରୋ',
    'aipro.subtitle': 'ଉନ୍ନତ AI-ଚାଳିତ ଉପକରଣ ଏବଂ ଅନ୍ତର୍ଦୃଷ୍ଟି ସହିତ ଆପଣଙ୍କ କ୍ୟାରିୟରକୁ ସୁପରଚାର୍ଜ କରନ୍ତୁ',
    'aipro.aiRecommendations': 'AI ସୁପାରିଶ',
    'aipro.successRate': 'ସଫଳତା ହାର',
    'aipro.aiAssistant': 'AI ସହାୟକ',
    'aipro.aiPoweredFeatures': '🚀 AI-ଚାଳିତ ବିଶେଷତା',
    'aipro.chooseYourPlan': '💎 ଆପଣଙ୍କ AI ପ୍ରୋ ପ୍ଲାନ୍ ବାଛନ୍ତୁ',
    'aipro.successStories': '🌟 ସଫଳତାର କାହାଣୀ',
    'aipro.mostPopular': 'ସବୁଠାରୁ ଲୋକପ୍ରିୟ',
    'aipro.startFreeTrial': 'ମାଗଣା ଟ୍ରାଏଲ୍ ଆରମ୍ଭ କରନ୍ତୁ',
    'aipro.getStarted': 'ଆରମ୍ଭ କରନ୍ତୁ',
    'aipro.careerGuidance': 'AI କ୍ୟାରିୟର ମାର୍ଗଦର୍ଶନ',
    'aipro.careerGuidanceDesc': 'ଉନ୍ନତ ମେସିନ୍ ଲର୍ନିଂ ଦ୍ୱାରା ଚାଳିତ ବ୍ୟକ୍ତିଗତ କ୍ୟାରିୟର ସୁପାରିଶ ପାଆନ୍ତୁ',
    'aipro.smartMatching': 'ସ୍ମାର୍ଟ ଜବ୍ ମ୍ୟାଚିଂ',
    'aipro.smartMatchingDesc': 'ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ଆଧାରରେ 95% ସଠିକତା ସହିତ AI-ଚାଳିତ ଜବ୍ ସୁପାରିଶ',
    'aipro.skillAnalysis': 'ସ୍କିଲ୍ ଗ୍ୟାପ୍ ଆନାଲିସିସ୍',
    'aipro.skillAnalysisDesc': 'ବଜାର ଚାହିଦା ବନାମ ଆପଣଙ୍କ କୌଶଳର ଉନ୍ନତ AI ବିଶ୍ଳେଷଣ',
    'aipro.interviewCoach': 'AI ଇଣ୍ଟରଭ୍ୟୁ କୋଚ୍',
    'aipro.interviewCoachDesc': 'AI ଇଣ୍ଟରଭ୍ୟୁଅର ସହିତ ଅଭ୍ୟାସ କରନ୍ତୁ ଏବଂ ରିଅଲ୍-ଟାଇମ୍ ଫିଡବ୍ୟାକ୍ ପାଆନ୍ତୁ',
    'aipro.resumeOptimizer': 'ରିଜ୍ୟୁମ୍ AI ଅପ୍ଟିମାଇଜର',
    'aipro.resumeOptimizerDesc': 'ATS ଅପ୍ଟିମାଇଜେସନ୍ ସହିତ AI-ଚାଳିତ ରିଜ୍ୟୁମ୍ ବିଶ୍ଳେଷଣ',
    'aipro.marketInsights': 'AI ମାର୍କେଟ୍ ଇନସାଇଟ୍ସ',
    'aipro.marketInsightsDesc': 'ରିଅଲ୍-ଟାଇମ୍ ମାର୍କେଟ୍ ବିଶ୍ଳେଷଣ ଏବଂ ବେତନ ପୂର୍ବାନୁମାନ',
    'aipro.mentorMatching': 'AI ମେଣ୍ଟର ମ୍ୟାଚିଂ',
    'aipro.mentorMatchingDesc': 'AI ସୁସଙ୍ଗତତା ବିଶ୍ଳେଷଣ ବ୍ୟବହାର କରି ପରଫେକ୍ଟ ମେଣ୍ଟର ଖୋଜନ୍ତୁ',
    'aipro.personalizedLearning': 'ବ୍ୟକ୍ତିଗତ ଶିକ୍ଷା',
    'aipro.personalizedLearningDesc': 'ଆପଣଙ୍କ କ୍ୟାରିୟର ଲକ୍ଷ୍ୟ ଆଧାରରେ AI-କ୍ୟୁରେଟେଡ୍ ଲର୍ନିଂ ପାଥ୍',
    'aipro.salaryNegotiator': 'AI ସାଲାରି ନେଗୋସିଏଟର',
    'aipro.salaryNegotiatorDesc': 'AI-ଚାଳିତ ବେତନ ବୁଝାମଣା ରଣନୀତି ଏବଂ ବଜାର ଡାଟା',
    'aipro.networkBuilder': 'AI ନେଟୱାର୍କ ବିଲ୍ଡର',
    'aipro.networkBuilderDesc': 'ସ୍ମାର୍ଟ ନେଟୱାର୍କିଂ ସୁପାରିଶ ଏବଂ ସଂଯୋଗ ରଣନୀତି',
    'aipro.careerPredictor': 'କ୍ୟାରିୟର ପାଥ୍ ପ୍ରେଡିକ୍ଟର',
    'aipro.careerPredictorDesc': 'ଆପଣଙ୍କ କ୍ୟାରିୟର ଟ୍ରାଜେକ୍ଟୋରୀ ଏବଂ ସୁଯୋଗ ପାଇଁ AI ପୂର୍ବାନୁମାନ',
    'aipro.portfolioBuilder': 'AI ପୋର୍ଟଫୋଲିଓ ବିଲ୍ଡର',
    'aipro.portfolioBuilderDesc': 'AI-ଜେନେରେଟେଡ୍ କଣ୍ଟେଣ୍ଟ ଏବଂ ଡିଜାଇନ୍ ସହିତ ଚମତ୍କାର ପୋର୍ଟଫୋଲିଓ ତିଆରି କରନ୍ତୁ',
    
    // Common Sections
    'common.internships': 'ଇଣ୍ଟର୍ନସିପ୍',
    'common.networking': 'ନେଟୱାର୍କିଂ',
    'common.mockPractice': 'ମକ୍ ଅଭ୍ୟାସ',
    'common.applyNow': 'ଏବେ ଆବେଦନ କରନ୍ତୁ',
    'common.learnMore': 'ଅଧିକ ଜାଣନ୍ତୁ',
    'common.viewAll': 'ସମସ୍ତ ଦେଖନ୍ତୁ',
    
    // Networking Section
    'networking.title': 'ସଂଯୋଗ ଏବଂ ନେଟୱାର୍କ',
    'networking.mentors': 'ମେଣ୍ଟର',
    'networking.alumni': 'ପୂର୍ବତନ ଛାତ୍ର',
    'networking.peers': 'ସାଥୀ',
    'networking.connectNow': 'ଏବେ ସଂଯୋଗ କରନ୍ତୁ',
    'networking.bookSession': 'ସେସନ୍ ବୁକ୍ କରନ୍ତୁ',
    'networking.sendMessage': 'ସନ୍ଦେଶ ପଠାନ୍ତୁ',
    'networking.years': 'ବର୍ଷ',
    'networking.sessions': 'ସେସନ୍',
    
    // Mock Practice Section
    'mockPractice.title': 'ମକ୍ ଅଭ୍ୟାସ ଏବଂ ଇଣ୍ଟରଭ୍ୟୁ',
    'mockPractice.technicalInterview': 'ବୈଷୟିକ ଇଣ୍ଟରଭ୍ୟୁ',
    'mockPractice.behavioralInterview': 'ଆଚରଣଗତ ଇଣ୍ଟରଭ୍ୟୁ',
    'mockPractice.caseStudy': 'କେସ୍ ଷ୍ଟଡି',
    'mockPractice.startPractice': 'ଅଭ୍ୟାସ ଆରମ୍ଭ କରନ୍ତୁ',
    'mockPractice.difficulty': 'କଠିନତା',
    'mockPractice.duration': 'ଅବଧି',
    'mockPractice.earnBadges': 'ବ୍ୟାଜ୍ ଅର୍ଜନ କରନ୍ତୁ',
    'mockPractice.unlockAchievements': 'ଚ୍ୟାଲେଞ୍ଜ ସମ୍ପୂର୍ଣ୍ଣ କରିବା ସମୟରେ ସଫଳତା ଅନଲକ୍ କରନ୍ତୁ',
    
    // Games Content
    'games.logicLoop': 'LogicLoop',
    'games.careerXP': 'CareerXP',
    'games.logicCoding': 'ଲଜିକ୍ ଏବଂ କୋଡିଂ',
    'games.careerSimulation': 'କ୍ୟାରିୟର ସିମୁଲେସନ୍',
    'games.intermediate': 'ମଧ୍ୟମ',
    'games.beginner': 'ଆରମ୍ଭକାରୀ',
    'games.advanced': 'ଉନ୍ନତ',
    'games.minPerSession': 'ମିନିଟ୍ ପ୍ରତି ସେସନ୍',
    'games.minPerChallenge': 'ମିନିଟ୍ ପ୍ରତି ଚ୍ୟାଲେଞ୍ଜ',
    'games.masterCoding': 'ଇଣ୍ଟରାକ୍ଟିଭ MCQ ଚ୍ୟାଲେଞ୍ଜ ମାଧ୍ୟମରେ କୋଡିଂ ଲଜିକ୍ରେ ଦକ୍ଷତା ହାସଲ କରନ୍ତୁ ଯାହା ଆପଣଙ୍କ ସମସ୍ୟା-ସମାଧାନ କୌଶଳ ପରୀକ୍ଷା କରେ।',
    'games.progressAlgorithmic': 'ଆଲଗୋରିଦମିକ୍ ପଜଲ୍, ଡାଟା ଷ୍ଟ୍ରକଚର ପ୍ରଶ୍ନ ଏବଂ ପ୍ରୋଗ୍ରାମିଂ ଧାରଣା ମାଧ୍ୟମରେ ଅଗ୍ରଗତି କରନ୍ତୁ।',
    'games.competeRealTime': 'ରିଅଲ୍-ଟାଇମ୍ ଲଜିକ୍ ବ୍ୟାଟଲରେ ସାଥୀମାନଙ୍କ ସହିତ ପ୍ରତିଯୋଗିତା କରନ୍ତୁ ଏବଂ ଗ୍ଲୋବାଲ୍ ଲିଡରବୋର୍ଡରେ ଚଢ଼ନ୍ତୁ।',
    'games.unlockAdvanced': 'ଡାଇନାମିକ୍ ପ୍ରୋଗ୍ରାମିଂ, ଗ୍ରାଫ୍ ଥିଓରୀ ଏବଂ ସିଷ୍ଟମ୍ ଡିଜାଇନ୍ ପରି ଉନ୍ନତ ବିଷୟ ଅନଲକ୍ କରନ୍ତୁ।',
    'games.createAvatar': 'ଆପଣଙ୍କର ପେଶାଦାର ଅବତାର ସୃଷ୍ଟି କରନ୍ତୁ ଏବଂ ବାସ୍ତବିକ କ୍ୟାରିୟର ଚ୍ୟାଲେଞ୍ଜରେ ଯାତ୍ରା କରନ୍ତୁ।',
    'games.buildResumes': 'ରିଜ୍ୟୁମ୍ ନିର୍ମାଣ କରନ୍ତୁ, ଇଣ୍ଡଷ୍ଟ୍ରି ପଜଲ୍ ସମାଧାନ କରନ୍ତୁ ଏବଂ ଇମର୍ସିଭ ପରିସ୍ଥିତିରେ ମିନି-ଇଣ୍ଟରଭ୍ୟୁ ଅଭ୍ୟାସ କରନ୍ତୁ।',
    'games.progressJobRoles': 'ବିଭିନ୍ନ ଚାକିରି ଭୂମିକା ମାଧ୍ୟମରେ ଅଗ୍ରଗତି କରନ୍ତୁ ଏବଂ ପ୍ରକୃତ କମ୍ପାନୀ ଉପରେ ଆଧାରିତ କ୍ୟାରିୟର କାହାଣୀ ଅନଲକ୍ କରନ୍ତୁ।',
    'games.earnBadgesPoints': 'ସ୍ତର ମାଧ୍ୟମରେ ଆଗକୁ ବଢ଼ିବା ସମୟରେ ବ୍ୟାଜ୍, ସ୍କିଲ୍ ପଏଣ୍ଟ ଏବଂ ମେଣ୍ଟରସିପ୍ ସୁଯୋଗ ଅର୍ଜନ କରନ୍ତୁ।',
    'games.moreInfo': 'ଅଧିକ ସୂଚନା',
    'games.badgesEarned': 'ଅର୍ଜିତ ବ୍ୟାଜ୍',
    'games.inProgress': 'ପ୍ରଗତିରେ',
    'games.completionRate': 'ସମ୍ପୂର୍ଣ୍ଣତା ହାର',
    'games.earnedBadges': 'ଅର୍ଜିତ ବ୍ୟାଜ୍',
    
    // Badge Names and Descriptions
    'badges.codeMaster': 'କୋଡ୍ ମାଷ୍ଟର',
    'badges.codeMasterDesc': '50 କୋଡିଂ ଚ୍ୟାଲେଞ୍ଜ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ',
    'badges.aiExplorer': 'AI ଏକ୍ସପ୍ଲୋରର',
    'badges.aiExplorerDesc': 'AI ଲର୍ନିଂ ପାଥ୍ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ',
    'badges.quickLearner': 'ଦ୍ରୁତ ଶିକ୍ଷାର୍ଥୀ',
    'badges.quickLearnerDesc': 'ରେକର୍ଡ ସମୟରେ କୋର୍ସ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ',
    'badges.profilePro': 'ପ୍ରୋଫାଇଲ୍ ପ୍ରୋ',
    'badges.profileProDesc': 'ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ 100% ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ',
    'badges.legendary': 'କିମ୍ବଦନ୍ତୀ',
    'badges.epic': 'ଏପିକ୍',
    'badges.rare': 'ବିରଳ',
    'badges.common': 'ସାଧାରଣ',
    
    // Mentor Events
    'mentorEvents.resumeReview': 'ପ୍ରିୟାଙ୍କ ସହିତ ରିଜ୍ୟୁମ୍ ସମୀକ୍ଷା',
    'mentorEvents.systemDesign': 'ଆକାଶଙ୍କ ସହିତ ସିଷ୍ଟମ୍ ଡିଜାଇନ୍ ମାଷ୍ଟରକ୍ଲାସ',
    'mentorEvents.aiCareerGuidance': 'AI କ୍ୟାରିୟର ମାର୍ଗଦର୍ଶନ ସେସନ୍',
    'mentorEvents.joinButton': 'ଯୋଗ ଦିଅନ୍ତୁ',
    'mentorEvents.viewAllEvents': 'ସମସ୍ତ ଇଭେଣ୍ଟ ଦେଖନ୍ତୁ',
    
    // Language Selector
    'language.english': 'English',
    'language.hindi': 'हिंदी',
    'language.odia': 'ଓଡ଼ିଆ'
  }
};

export default LanguageContext;